Update for macOS 13 Ventura (clean install)
== pcre2

It seems between macOS 10.15 and macOS 13, Apple stopped providing
pcre2. Either that, or whatever means Homebrew uses to install, is
no longer being picked up when pecl compiles extensions. The latter
could make sense, e.g. if `pecl` and `php-config` have a CFLAGS
default that includes the (by default non-existent) /usr/local/include/
directory, which is where Homebrew used to symlink header files.
But, given the switch to /opt/homebrew, these are now linked from
/opt/homebrew/include/, which it wouldn't know about by defaut.

The result is that `pecl install apcu` worked on macOS 10.15, but
fails by default on macOS 13:

> $ pecl install apcu
> …
> /opt/homebrew/Cellar/php/8.2.8/include/php/ext/pcre/php_pcre.h:23:10:
> fatal error: 'pcre2.h' file not found

Ideally, Homebrew would fix the packaging of pecl or php-config such
that CFLAGS defaults to at least picking up /opt/homebrew/include/.
But alas, it doesn't.

Ref https://github.com/Homebrew/homebrew-core/issues/102392.

Workaround from https://stackoverflow.com/a/72612925/319266.

== hh

Homebrew's web interface still redirects for `hh`, but the alias no
longer works at install time. The package is now available as `hstr`.

== bash

Terminal app could previously auto-detect and offer /usr/local/bin/bash
as an available choice when installed via Homebrew in the settings app.

Now that Homebrew installs to /opt/homebrew instead, it seems the only
way to make this work, is to first modify /etc/shells and then run
`chsh` to change the default. Document and automate this for future
reference.

== Logi Options+

Despite the marketing materials, Logi Options+ "Plus", in fact
does not contain "all the features" of Logi Options. The "Look up"
mapping is, for instance, suspiciously missing from the capability
list. And when the basic "Click" feature of the mouse software is
removed in favour of new feature that releases the mouse immediately
upon mouse-down (thus making moving and dragging impossible),
no amount of rebranding it "Advanced click" makes it anything other
than broken.

== ssh

macOS 13 ships OpenSSH_9.0p1 (LibreSSL 3.3.6) whereas macOS 10.15
came with OpenSSH_8.1p (LibreSSL 2.7.3). This makes the difference
that it no longer tolerates RSA host keys by default.
Selective set `PubkeyAcceptedKeyTypes` as-needed to compensate.